name: test the library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # setup golang sdk
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    # install dependencies
    - name: Install dependencies
      run: go mod download
    # run tests
    - name: Run tests
      run: go test -v ./...
      env:
        CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}